using Microsoft.Win32;
using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Windows.Forms;

namespace SmartHubRemote {
    public sealed class MainForm:Form {
        readonly Color Navy=Color.FromArgb(7,21,47),Panel=Color.FromArgb(16,38,75),Cyan=Color.FromArgb(25,216,255),Muted=Color.FromArgb(169,188,214);
        RemoteServer server; BluetoothSerialBridge bluetooth; Label status,ip,pinLabel,clients,log; ComboBox ports; CheckBox startup; NotifyIcon tray; Timer clipTimer; string lastClipboard=""; string pin;
        public MainForm(){Text="SmartHub Remote Companion";Size=new Size(760,570);MinimumSize=new Size(700,520);StartPosition=FormStartPosition.CenterScreen;BackColor=Navy;ForeColor=Color.White;Font=new Font("Segoe UI",10);BuildUi();LoadSettings();Shown+=(s,e)=>StartServer();}
        void BuildUi(){
            var header=new Panel{Dock=DockStyle.Top,Height=96,BackColor=Color.FromArgb(10,30,62),Padding=new Padding(18)};Controls.Add(header);
            var logo=new PictureBox{Location=new Point(18,12),Size=new Size(70,70),SizeMode=PictureBoxSizeMode.Zoom};string logoPath=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Assets","logo.png");if(File.Exists(logoPath))logo.Image=Image.FromFile(logoPath);header.Controls.Add(logo);
            header.Controls.Add(new Label{Text="SmartHub Remote",Font=new Font("Segoe UI",22,FontStyle.Bold),ForeColor=Color.White,AutoSize=true,Location=new Point(103,15)});
            status=new Label{Text="Starting…",ForeColor=Cyan,AutoSize=true,Location=new Point(106,57)};header.Controls.Add(status);
            var about=ButtonAt("About",590,24,110,44);about.Anchor=AnchorStyles.Top|AnchorStyles.Right;about.Click+=(s,e)=>ShowAbout();header.Controls.Add(about);
            var info=Card(new Point(18,114),new Size(706,120));Controls.Add(info);info.Controls.Add(LabelAt("PC address",18,14,Muted));ip=LabelAt("Detecting…",18,42,Color.White,15,true);info.Controls.Add(ip);info.Controls.Add(LabelAt("Pairing PIN",355,14,Muted));pinLabel=LabelAt("------",355,40,Cyan,25,true);info.Controls.Add(pinLabel);var newPin=ButtonAt("New PIN",555,39,120,42);newPin.Click+=(s,e)=>{pin=NewPin();SavePin();pinLabel.Text=pin;server.Pin=pin;};info.Controls.Add(newPin);
            var settings=Card(new Point(18,250),new Size(345,200));Controls.Add(settings);settings.Controls.Add(LabelAt("Connection & startup",18,16,Color.White,14,true));clients=LabelAt("Connected devices: 0",18,52,Muted);settings.Controls.Add(clients);startup=new CheckBox{Text="Start with Windows",AutoSize=true,Location=new Point(18,86),ForeColor=Color.White,BackColor=Color.Transparent};startup.CheckedChanged+=(s,e)=>SetStartup(startup.Checked);settings.Controls.Add(startup);var firewall=ButtonAt("Add Private Firewall Rule",18,124,280,42);firewall.Click+=(s,e)=>AddFirewall();settings.Controls.Add(firewall);
            var bt=Card(new Point(379,250),new Size(345,200));Controls.Add(bt);bt.Controls.Add(LabelAt("Bluetooth (paired COM port)",18,16,Color.White,14,true));ports=new ComboBox{Location=new Point(18,55),Width=190,DropDownStyle=ComboBoxStyle.DropDownList};bt.Controls.Add(ports);var refresh=ButtonAt("Refresh",220,53,95,34);refresh.Click+=(s,e)=>RefreshPorts();bt.Controls.Add(refresh);var startBt=ButtonAt("Start Bluetooth",18,105,297,42);startBt.Click+=(s,e)=>StartBluetooth();bt.Controls.Add(startBt);bt.Controls.Add(LabelAt("Best for mouse/keyboard. Use Wi-Fi for screen.",18,157,Muted,9));
            log=new Label{Text="Ready",AutoEllipsis=true,Location=new Point(24,468),Size=new Size(690,45),ForeColor=Muted};Controls.Add(log);RefreshPorts();
            tray=new NotifyIcon{Visible=true,Text="SmartHub Remote",Icon=Icon};tray.DoubleClick+=(s,e)=>{Show();WindowState=FormWindowState.Normal;Activate();};tray.ContextMenu=new ContextMenu(new[]{new MenuItem("Open",(s,e)=>Show()),new MenuItem("Exit",(s,e)=>{tray.Visible=false;Application.Exit();})});
            clipTimer=new Timer{Interval=700};clipTimer.Tick+=(s,e)=>WatchClipboard();clipTimer.Start();Resize+=(s,e)=>{if(WindowState==FormWindowState.Minimized)Hide();};FormClosing+=(s,e)=>{if(e.CloseReason==CloseReason.UserClosing){e.Cancel=true;Hide();tray.ShowBalloonTip(1200,"SmartHub Remote","Companion is still running.",ToolTipIcon.Info);}};
        }
        Panel Card(Point p,Size s){return new Panel{Location=p,Size=s,BackColor=Panel,Padding=new Padding(8)};}Label LabelAt(string text,int x,int y,Color c,float size=10,bool bold=false){return new Label{Text=text,Location=new Point(x,y),AutoSize=true,ForeColor=c,Font=new Font("Segoe UI",size,bold?FontStyle.Bold:FontStyle.Regular)};}Button ButtonAt(string text,int x,int y,int w,int h){return new Button{Text=text,Location=new Point(x,y),Size=new Size(w,h),BackColor=Color.FromArgb(38,118,255),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};}
        void LoadSettings(){string f=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"SmartHubRemote","pin.txt");if(File.Exists(f))pin=File.ReadAllText(f).Trim();if(string.IsNullOrWhiteSpace(pin)||pin.Length!=6)pin=NewPin();SavePin();pinLabel.Text=pin;startup.Checked=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run")?.GetValue("SmartHubRemote")!=null;}
        void SavePin(){string d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),"SmartHubRemote");Directory.CreateDirectory(d);File.WriteAllText(Path.Combine(d,"pin.txt"),pin);}
        string NewPin(){return new Random(Guid.NewGuid().GetHashCode()).Next(100000,999999).ToString();}
        void StartServer(){server=new RemoteServer(this,pin);server.Log+=x=>PostToUi(()=>log.Text=DateTime.Now.ToString("HH:mm:ss")+"  "+x);server.ClientCountChanged+=n=>PostToUi(()=>clients.Text="Connected devices: "+n);try{server.Start();status.Text="Online • waiting for phone";ip.Text=LocalAddresses()+"  : 18788";}catch(Exception e){status.Text="Server error";log.Text=e.Message;}bluetooth=new BluetoothSerialBridge(server);bluetooth.Log+=x=>PostToUi(()=>log.Text=x);}
        void PostToUi(Action action){if(IsDisposed||Disposing||!IsHandleCreated)return;try{if(InvokeRequired)BeginInvoke(action);else action();}catch(InvalidOperationException){}}
        string LocalAddresses(){try{return string.Join("  •  ",Dns.GetHostAddresses(Dns.GetHostName()).Where(a=>a.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(a)).Select(a=>a.ToString()));}catch{return "127.0.0.1";}}
        void WatchClipboard(){try{if(!Clipboard.ContainsText())return;string t=Clipboard.GetText();if(t==lastClipboard)return;lastClipboard=t;server?.BroadcastClipboard(t);}catch{}}
        void RefreshPorts(){string selected=ports.SelectedItem as string;ports.Items.Clear();ports.Items.AddRange(BluetoothSerialBridge.Ports());if(selected!=null&&ports.Items.Contains(selected))ports.SelectedItem=selected;else if(ports.Items.Count>0)ports.SelectedIndex=0;}
        void StartBluetooth(){if(ports.SelectedItem==null){MessageBox.Show("Pair the phone in Windows Bluetooth settings and create/select its COM port.");return;}try{bluetooth.Start(ports.SelectedItem.ToString());status.Text="Wi-Fi + Bluetooth online";}catch(Exception e){MessageBox.Show(e.Message,"Bluetooth");}}
        void SetStartup(bool on){try{using(var k=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run",true)){if(on)k.SetValue("SmartHubRemote","\""+Application.ExecutablePath+"\" --minimized");else k.DeleteValue("SmartHubRemote",false);}}catch(Exception e){MessageBox.Show(e.Message);}}
        void AddFirewall(){try{string args="/c netsh advfirewall firewall add rule name=\"SmartHub Remote TCP\" dir=in action=allow protocol=TCP localport=18788 profile=private & netsh advfirewall firewall add rule name=\"SmartHub Remote Discovery\" dir=in action=allow protocol=UDP localport=18789 profile=private";var p=new System.Diagnostics.ProcessStartInfo("cmd.exe",args){Verb="runas",UseShellExecute=true};System.Diagnostics.Process.Start(p);MessageBox.Show("Private-network firewall rules requested.");}catch(Exception e){MessageBox.Show(e.Message);}}
        void ShowAbout(){var f=new Form{Text="About SmartHub Remote",Size=new Size(470,500),StartPosition=FormStartPosition.CenterParent,BackColor=Navy,ForeColor=Color.White,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false};var pic=new PictureBox{Location=new Point(170,25),Size=new Size(110,110),SizeMode=PictureBoxSizeMode.Zoom};string p=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Assets","logo.png");if(File.Exists(p))pic.Image=Image.FromFile(p);f.Controls.Add(pic);var title=LabelAt("SmartHub Remote",0,150,Color.White,24,true);title.Width=450;title.TextAlign=ContentAlignment.MiddleCenter;f.Controls.Add(title);var version=LabelAt("Version 1.1.3  •  Premium Remote Suite",0,194,Cyan,10);version.Width=450;version.TextAlign=ContentAlignment.MiddleCenter;f.Controls.Add(version);var made=LabelAt("DESIGNED & DEVELOPED BY",0,250,Muted,9);made.Width=450;made.TextAlign=ContentAlignment.MiddleCenter;f.Controls.Add(made);var company=LabelAt("SMART HUB TECHNOLOGY",0,278,Color.White,17,true);company.Width=450;company.TextAlign=ContentAlignment.MiddleCenter;f.Controls.Add(company);var detail=LabelAt("Private local control • Secure PIN pairing\nMouse • Keyboard • Screen • Files • Media",0,330,Muted,11);detail.Width=450;detail.Height=55;detail.TextAlign=ContentAlignment.MiddleCenter;f.Controls.Add(detail);var close=ButtonAt("Close",145,404,160,44);close.Click+=(s,e)=>f.Close();f.Controls.Add(close);f.ShowDialog(this);}
        protected override void Dispose(bool disposing){if(disposing){clipTimer?.Dispose();bluetooth?.Dispose();server?.Dispose();if(tray!=null){tray.Visible=false;tray.Dispose();}}base.Dispose(disposing);}
    }
}
