using System;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SmartHubRemote {
    internal sealed class PhoneControllerForm:Form {
        readonly Color Navy=Color.FromArgb(7,21,47),Panel=Color.FromArgb(16,38,75),Cyan=Color.FromArgb(25,216,255),Muted=Color.FromArgb(169,188,214);readonly PhoneControllerClient client=new PhoneControllerClient();readonly OnlinePhoneControllerClient onlineClient=new OnlinePhoneControllerClient();
        TextBox host,pin,text;Label status;PictureBox screen;Timer frameTimer;Button mode,find;volatile bool loading,onlineMode;Point down;Stopwatch press=new Stopwatch();
        public PhoneControllerForm(){Text="SmartHub Phone Controller";Size=new Size(520,760);MinimumSize=new Size(450,620);StartPosition=FormStartPosition.CenterParent;BackColor=Navy;ForeColor=Color.White;Font=new Font("Segoe UI",10);Build();client.Status+=x=>Post(()=>status.Text=x);onlineClient.Status+=x=>Post(()=>status.Text=x);onlineClient.Frame+=ShowFrame;}
        void Build(){var title=new Label{Text="SmartHub • Control Phone",Font=new Font("Segoe UI",20,FontStyle.Bold),ForeColor=Color.White,Location=new Point(18,15),AutoSize=true};Controls.Add(title);status=new Label{Text="The target phone must enable Control and Share Screen",ForeColor=Cyan,Location=new Point(21,53),AutoSize=true};Controls.Add(status);
            mode=Btn("LAN",18,82,62,38);mode.Click+=(s,e)=>ToggleMode();Controls.Add(mode);host=Box("Phone IP",87,82,180);pin=Box("6-digit PIN",274,82,102);pin.PasswordChar='●';Controls.Add(host);Controls.Add(pin);find=Btn("Find",383,82,53,38);find.Click+=(s,e)=>FindPhone();Controls.Add(find);var connect=Btn("Connect",442,82,62,38,true);connect.Click+=(s,e)=>ConnectPhone();Controls.Add(connect);
            screen=new PictureBox{Location=new Point(18,132),Size=new Size(486,470),BackColor=Color.Black,SizeMode=PictureBoxSizeMode.StretchImage,Anchor=AnchorStyles.Top|AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right};screen.MouseDown+=(s,e)=>{down=e.Location;press.Restart();};screen.MouseUp+=(s,e)=>SendPointer(e.Location);Controls.Add(screen);
            var back=Btn("‹ Back",18,613,110,40);var home=Btn("● Home",136,613,110,40,true);var recent=Btn("▢ Recent",254,613,110,40);var notices=Btn("Notifications",372,613,132,40);back.Click+=(s,e)=>Global("back");home.Click+=(s,e)=>Global("home");recent.Click+=(s,e)=>Global("recents");notices.Click+=(s,e)=>Global("notifications");foreach(var b in new[]{back,home,recent,notices}){b.Anchor=AnchorStyles.Bottom|AnchorStyles.Left;Controls.Add(b);}
            text=Box("Type on the remote phone",18,665,245);text.Anchor=AnchorStyles.Bottom|AnchorStyles.Left|AnchorStyles.Right;Controls.Add(text);var file=Btn("Send File",271,665,112,38);file.Anchor=AnchorStyles.Bottom|AnchorStyles.Right;file.Click+=(s,e)=>SendFile();Controls.Add(file);var send=Btn("Send Text",391,665,113,38,true);send.Anchor=AnchorStyles.Bottom|AnchorStyles.Right;send.Click+=(s,e)=>{if(text.TextLength>0){if(onlineMode)onlineClient.Text(text.Text);else client.Text(text.Text);text.Clear();}};Controls.Add(send);frameTimer=new Timer{Interval=220};frameTimer.Tick+=(s,e)=>LoadFrame();frameTimer.Start();Resize+=(s,e)=>{screen.Width=ClientSize.Width-36;screen.Height=Math.Max(250,ClientSize.Height-278);int bottom=ClientSize.Height-108;back.Top=home.Top=recent.Top=notices.Top=bottom;text.Top=file.Top=send.Top=bottom+52;};}
        TextBox Box(string hint,int x,int y,int w){return new TextBox{Text=hint,Location=new Point(x,y),Size=new Size(w,38),BackColor=Panel,ForeColor=Color.White,BorderStyle=BorderStyle.FixedSingle};}
        Button Btn(string t,int x,int y,int w,int h,bool primary=false){return new Button{Text=t,Location=new Point(x,y),Size=new Size(w,h),BackColor=primary?Color.FromArgb(38,118,255):Panel,ForeColor=Color.White,FlatStyle=FlatStyle.Flat};}
        async void FindPhone(){status.Text="Searching local Wi-Fi…";try{string found=await Task.Run(()=>PhoneControllerClient.Discover());host.Text=found;status.Text="Phone found • "+found;}catch(Exception e){status.Text="Phone not found • "+e.Message;}}
        void ToggleMode(){onlineMode=!onlineMode;mode.Text=onlineMode?"ONLINE":"LAN";host.Text=onlineMode?"9-digit Online ID":"Phone IP";find.Enabled=!onlineMode;status.Text=onlineMode?"Enter Online ID and current PIN":"The target phone must enable Control and Share Screen";}
        async void ConnectPhone(){string hint=onlineMode?"9-digit Online ID":"Phone IP",h=Clean(host.Text,hint),p=Clean(pin.Text,"6-digit PIN");if((onlineMode?h.Length!=9:h.Length==0)||p.Length!=6){MessageBox.Show(onlineMode?"Enter the 9-digit Online ID and six-digit PIN.":"Enter the phone IP and its six-digit Receiver PIN.");return;}status.Text="Connecting…";try{if(onlineMode)await onlineClient.Connect(h,p);else await Task.Run(()=>client.Connect(h,p));status.Text=(onlineMode?"Online":"LAN")+" connected • touch the live phone screen";}catch(Exception e){status.Text="Connection failed • "+e.Message;}}
        string Clean(string value,string hint){return value==hint?"":value.Trim();}
        void Global(string action){if(onlineMode)onlineClient.Global(action);else client.Global(action);}
        void SendPointer(Point up){if(onlineMode ? !onlineClient.Connected : !client.Connected)return;press.Stop();double x1=Math.Max(0,Math.Min(1,down.X/(double)screen.Width)),y1=Math.Max(0,Math.Min(1,down.Y/(double)screen.Height)),x2=Math.Max(0,Math.Min(1,up.X/(double)screen.Width)),y2=Math.Max(0,Math.Min(1,up.Y/(double)screen.Height));if(Math.Abs(up.X-down.X)+Math.Abs(up.Y-down.Y)>24){if(onlineMode)onlineClient.Swipe(x1,y1,x2,y2,press.ElapsedMilliseconds);else client.Swipe(x1,y1,x2,y2,press.ElapsedMilliseconds);}else{if(onlineMode)onlineClient.Tap(x2,y2);else client.Tap(x2,y2);}}
        async void SendFile(){if(onlineMode){MessageBox.Show("Fast file transfer is LAN-only. Switch to LAN mode and keep both devices on the same Wi-Fi.");return;}string h=Clean(host.Text,"Phone IP"),p=Clean(pin.Text,"6-digit PIN");if(h.Length==0||p.Length!=6){MessageBox.Show("Connect to the receiver phone on LAN first.");return;}using(var pick=new OpenFileDialog()){pick.Title="Send file to phone";if(pick.ShowDialog(this)!=DialogResult.OK)return;status.Text="Sending file…";try{await FastFileClient.Send(pick.FileName,h,p,x=>Post(()=>status.Text="Sending file • "+x+"%"));status.Text="File saved on phone • Downloads/SmartHub Remote";}catch(Exception e){status.Text="File transfer failed • "+e.Message;}}}
        async void LoadFrame(){if(onlineMode||!client.Connected||loading)return;string h=Clean(host.Text,"Phone IP");if(h.Length==0)return;loading=true;try{byte[] data=await Task.Run(()=>{using(var wc=new WebClient()){wc.Headers[HttpRequestHeader.CacheControl]="no-cache";return wc.DownloadData("http://"+h+":18791/frame.jpg?t="+DateTime.UtcNow.Ticks);}});ShowFrame(data);}catch{}finally{loading=false;}}
        void ShowFrame(byte[] data){Post(()=>{try{using(var ms=new MemoryStream(data))using(var source=Image.FromStream(ms)){var copy=new Bitmap(source);var old=screen.Image;screen.Image=copy;if(old!=null)old.Dispose();}}catch{}});}
        void Post(Action a){if(IsDisposed)return;try{if(InvokeRequired)BeginInvoke(a);else a();}catch{}}
        protected override void Dispose(bool disposing){if(disposing){frameTimer?.Dispose();client.Dispose();onlineClient.Dispose();if(screen!=null&&screen.Image!=null)screen.Image.Dispose();}base.Dispose(disposing);}
    }
}
